### Get all playlists
GET {{host}}:{{port}}/api/playlists

### Create playlists
POST {{host}}:{{port}}/api/playlists
Content-Type: application/json

[
  {
    "name": "new playlist name"
  }
]

### Get Playlist Media
GET {{host}}:{{port}}/api/playlists/66824bba-5efc-49cb-9818-7d4792de9404/media

### Add media to playlist
PUT {{host}}:{{port}}/api/playlists/f3eacff9-b536-4ff8-8e67-d814c1569071/media
Content-Type: application/json

[{"mediaId": "32f81139-368f-437a-885f-065a4e1b70c8"}]

### Delete playlist
DELETE {{host}}:{{port}}/api/playlists/f3eacff9-b536-4ff8-8e67-d814c1569071
