// Code generated by MockGen. DO NOT EDIT.
// Source: ./apps/server/internal/service/media/media.go
//
// Generated by this command:
//
//	mockgen -source=./apps/server/internal/service/media/media.go
//

// Package mock_mediaService is a generated GoMock package.
package mock_mediaService

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/slugger7/exorcist/apps/server/internal/db/exorcist/public/model"
	dto "github.com/slugger7/exorcist/apps/server/internal/dto"
	models "github.com/slugger7/exorcist/apps/server/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMediaService is a mock of MediaService interface.
type MockMediaService struct {
	ctrl     *gomock.Controller
	recorder *MockMediaServiceMockRecorder
	isgomock struct{}
}

// MockMediaServiceMockRecorder is the mock recorder for MockMediaService.
type MockMediaServiceMockRecorder struct {
	mock *MockMediaService
}

// NewMockMediaService creates a new mock instance.
func NewMockMediaService(ctrl *gomock.Controller) *MockMediaService {
	mock := &MockMediaService{ctrl: ctrl}
	mock.recorder = &MockMediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaService) EXPECT() *MockMediaServiceMockRecorder {
	return m.recorder
}

// AddPerson mocks base method.
func (m *MockMediaService) AddPerson(id, personId uuid.UUID) (*model.MediaPerson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPerson", id, personId)
	ret0, _ := ret[0].(*model.MediaPerson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPerson indicates an expected call of AddPerson.
func (mr *MockMediaServiceMockRecorder) AddPerson(id, personId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPerson", reflect.TypeOf((*MockMediaService)(nil).AddPerson), id, personId)
}

// AddTag mocks base method.
func (m *MockMediaService) AddTag(id, tagId uuid.UUID) (*model.MediaTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", id, tagId)
	ret0, _ := ret[0].(*model.MediaTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTag indicates an expected call of AddTag.
func (mr *MockMediaServiceMockRecorder) AddTag(id, tagId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockMediaService)(nil).AddTag), id, tagId)
}

// CopyPeople mocks base method.
func (m *MockMediaService) CopyPeople(toId, fromId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyPeople", toId, fromId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyPeople indicates an expected call of CopyPeople.
func (mr *MockMediaServiceMockRecorder) CopyPeople(toId, fromId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyPeople", reflect.TypeOf((*MockMediaService)(nil).CopyPeople), toId, fromId)
}

// CopyTags mocks base method.
func (m *MockMediaService) CopyTags(toId, fromId uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyTags", toId, fromId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyTags indicates an expected call of CopyTags.
func (mr *MockMediaServiceMockRecorder) CopyTags(toId, fromId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyTags", reflect.TypeOf((*MockMediaService)(nil).CopyTags), toId, fromId)
}

// Delete mocks base method.
func (m *MockMediaService) Delete(id uuid.UUID, physical bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, physical)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMediaServiceMockRecorder) Delete(id, physical any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMediaService)(nil).Delete), id, physical)
}

// DeleteRelations mocks base method.
func (m *MockMediaService) DeleteRelations(id uuid.UUID, deleteDto dto.DeleteMediaRelationsDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRelations", id, deleteDto)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRelations indicates an expected call of DeleteRelations.
func (mr *MockMediaServiceMockRecorder) DeleteRelations(id, deleteDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRelations", reflect.TypeOf((*MockMediaService)(nil).DeleteRelations), id, deleteDto)
}

// GetByIdAndUserIdWithRelations mocks base method.
func (m *MockMediaService) GetByIdAndUserIdWithRelations(id, userId uuid.UUID, relationType *model.MediaRelationTypeEnum) (*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdAndUserIdWithRelations", id, userId, relationType)
	ret0, _ := ret[0].(*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdAndUserIdWithRelations indicates an expected call of GetByIdAndUserIdWithRelations.
func (mr *MockMediaServiceMockRecorder) GetByIdAndUserIdWithRelations(id, userId, relationType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdAndUserIdWithRelations", reflect.TypeOf((*MockMediaService)(nil).GetByIdAndUserIdWithRelations), id, userId, relationType)
}

// LogProgress mocks base method.
func (m *MockMediaService) LogProgress(id, userId uuid.UUID, progress dto.ProgressUpdateDTO) (*model.MediaProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogProgress", id, userId, progress)
	ret0, _ := ret[0].(*model.MediaProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogProgress indicates an expected call of LogProgress.
func (mr *MockMediaServiceMockRecorder) LogProgress(id, userId, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogProgress", reflect.TypeOf((*MockMediaService)(nil).LogProgress), id, userId, progress)
}

// Relate mocks base method.
func (m *MockMediaService) Relate(id uuid.UUID, relateDto dto.PutMediaRelationDto) ([]model.MediaRelation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Relate", id, relateDto)
	ret0, _ := ret[0].([]model.MediaRelation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Relate indicates an expected call of Relate.
func (mr *MockMediaServiceMockRecorder) Relate(id, relateDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Relate", reflect.TypeOf((*MockMediaService)(nil).Relate), id, relateDto)
}
